import = [
    # uncomment the flavour you want below:
    "~/.config/alacritty/themes/catppuccin-latte.toml",
    # "~/.config/alacritty/themes/catppuccin-frappe.toml"
    # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
    # "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[window.padding]
x = 6
y = 6

[font]
size = 13

[shell]
program = "/bin/fish"

[font.normal]
family = "JetBrains Mono Nerd Font Mono"
style = "Medium"
