import = [
    # uncomment the flavour you want below:
    "~/.config/alacritty/themes/catppuccin-latte.toml",
    # "~/.config/alacritty/themes/catppuccin-frappe.toml"
    # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
    # "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[font]
size = 12

[shell]
program = "/bin/fish"

[font.normal]
family = "JetBrains Mono"
style = "Regular"
